// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: service.proto

package lumenvecpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorService_Health_FullMethodName          = "/lumenvec.VectorService/Health"
	VectorService_ListVectors_FullMethodName     = "/lumenvec.VectorService/ListVectors"
	VectorService_AddVector_FullMethodName       = "/lumenvec.VectorService/AddVector"
	VectorService_AddVectorsBatch_FullMethodName = "/lumenvec.VectorService/AddVectorsBatch"
	VectorService_GetVector_FullMethodName       = "/lumenvec.VectorService/GetVector"
	VectorService_Search_FullMethodName          = "/lumenvec.VectorService/Search"
	VectorService_SearchBatch_FullMethodName     = "/lumenvec.VectorService/SearchBatch"
	VectorService_DeleteVector_FullMethodName    = "/lumenvec.VectorService/DeleteVector"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error)
	AddVector(ctx context.Context, in *AddVectorRequest, opts ...grpc.CallOption) (*AddVectorResponse, error)
	AddVectorsBatch(ctx context.Context, in *AddVectorsBatchRequest, opts ...grpc.CallOption) (*AddVectorsBatchResponse, error)
	GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, VectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVectorsResponse)
	err := c.cc.Invoke(ctx, VectorService_ListVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) AddVector(ctx context.Context, in *AddVectorRequest, opts ...grpc.CallOption) (*AddVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_AddVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) AddVectorsBatch(ctx context.Context, in *AddVectorsBatchRequest, opts ...grpc.CallOption) (*AddVectorsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVectorsBatchResponse)
	err := c.cc.Invoke(ctx, VectorService_AddVectorsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_GetVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, VectorService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBatchResponse)
	err := c.cc.Invoke(ctx, VectorService_SearchBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility.
type VectorServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error)
	AddVector(context.Context, *AddVectorRequest) (*AddVectorResponse, error)
	AddVectorsBatch(context.Context, *AddVectorsBatchRequest) (*AddVectorsBatchResponse, error)
	GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorServiceServer struct{}

func (UnimplementedVectorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVectorServiceServer) ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVectors not implemented")
}
func (UnimplementedVectorServiceServer) AddVector(context.Context, *AddVectorRequest) (*AddVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVector not implemented")
}
func (UnimplementedVectorServiceServer) AddVectorsBatch(context.Context, *AddVectorsBatchRequest) (*AddVectorsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVectorsBatch not implemented")
}
func (UnimplementedVectorServiceServer) GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVector not implemented")
}
func (UnimplementedVectorServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorServiceServer) SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBatch not implemented")
}
func (UnimplementedVectorServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}
func (UnimplementedVectorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	// If the following call panics, it indicates UnimplementedVectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ListVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ListVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ListVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ListVectors(ctx, req.(*ListVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_AddVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).AddVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_AddVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).AddVector(ctx, req.(*AddVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_AddVectorsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVectorsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).AddVectorsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_AddVectorsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).AddVectorsBatch(ctx, req.(*AddVectorsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GetVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GetVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GetVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GetVector(ctx, req.(*GetVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_SearchBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).SearchBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_SearchBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).SearchBatch(ctx, req.(*SearchBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumenvec.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VectorService_Health_Handler,
		},
		{
			MethodName: "ListVectors",
			Handler:    _VectorService_ListVectors_Handler,
		},
		{
			MethodName: "AddVector",
			Handler:    _VectorService_AddVector_Handler,
		},
		{
			MethodName: "AddVectorsBatch",
			Handler:    _VectorService_AddVectorsBatch_Handler,
		},
		{
			MethodName: "GetVector",
			Handler:    _VectorService_GetVector_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectorService_Search_Handler,
		},
		{
			MethodName: "SearchBatch",
			Handler:    _VectorService_SearchBatch_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _VectorService_DeleteVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	ClusterControl_Campaign_FullMethodName      = "/lumenvec.ClusterControl/Campaign"
	ClusterControl_EnsureLeader_FullMethodName  = "/lumenvec.ClusterControl/EnsureLeader"
	ClusterControl_AppendEntries_FullMethodName = "/lumenvec.ClusterControl/AppendEntries"
)

// ClusterControlClient is the client API for ClusterControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterControl is an internal, additive control-plane contract. It is
// intentionally separate from VectorService so data-plane clients remain
// compatible while nodes exchange election terms and fencing state.
type ClusterControlClient interface {
	Campaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	EnsureLeader(ctx context.Context, in *EnsureLeaderRequest, opts ...grpc.CallOption) (*EnsureLeaderResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type clusterControlClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterControlClient(cc grpc.ClientConnInterface) ClusterControlClient {
	return &clusterControlClient{cc}
}

func (c *clusterControlClient) Campaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, ClusterControl_Campaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) EnsureLeader(ctx context.Context, in *EnsureLeaderRequest, opts ...grpc.CallOption) (*EnsureLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureLeaderResponse)
	err := c.cc.Invoke(ctx, ClusterControl_EnsureLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, ClusterControl_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterControlServer is the server API for ClusterControl service.
// All implementations must embed UnimplementedClusterControlServer
// for forward compatibility.
//
// ClusterControl is an internal, additive control-plane contract. It is
// intentionally separate from VectorService so data-plane clients remain
// compatible while nodes exchange election terms and fencing state.
type ClusterControlServer interface {
	Campaign(context.Context, *CampaignRequest) (*CampaignResponse, error)
	EnsureLeader(context.Context, *EnsureLeaderRequest) (*EnsureLeaderResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	mustEmbedUnimplementedClusterControlServer()
}

// UnimplementedClusterControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterControlServer struct{}

func (UnimplementedClusterControlServer) Campaign(context.Context, *CampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Campaign not implemented")
}
func (UnimplementedClusterControlServer) EnsureLeader(context.Context, *EnsureLeaderRequest) (*EnsureLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureLeader not implemented")
}
func (UnimplementedClusterControlServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedClusterControlServer) mustEmbedUnimplementedClusterControlServer() {}
func (UnimplementedClusterControlServer) testEmbeddedByValue()                        {}

// UnsafeClusterControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterControlServer will
// result in compilation errors.
type UnsafeClusterControlServer interface {
	mustEmbedUnimplementedClusterControlServer()
}

func RegisterClusterControlServer(s grpc.ServiceRegistrar, srv ClusterControlServer) {
	// If the following call panics, it indicates UnimplementedClusterControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterControl_ServiceDesc, srv)
}

func _ClusterControl_Campaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).Campaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_Campaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).Campaign(ctx, req.(*CampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_EnsureLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).EnsureLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_EnsureLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).EnsureLeader(ctx, req.(*EnsureLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterControl_ServiceDesc is the grpc.ServiceDesc for ClusterControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumenvec.ClusterControl",
	HandlerType: (*ClusterControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Campaign",
			Handler:    _ClusterControl_Campaign_Handler,
		},
		{
			MethodName: "EnsureLeader",
			Handler:    _ClusterControl_EnsureLeader_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _ClusterControl_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	DataPlaneTransfer_ReservePrebuiltIDs_FullMethodName        = "/lumenvec.DataPlaneTransfer/ReservePrebuiltIDs"
	DataPlaneTransfer_UploadPrebuiltSnapshot_FullMethodName    = "/lumenvec.DataPlaneTransfer/UploadPrebuiltSnapshot"
	DataPlaneTransfer_ApplyPrebuiltSegment_FullMethodName      = "/lumenvec.DataPlaneTransfer/ApplyPrebuiltSegment"
	DataPlaneTransfer_BuildPrebuiltSegment_FullMethodName      = "/lumenvec.DataPlaneTransfer/BuildPrebuiltSegment"
	DataPlaneTransfer_ExportSealedANNRecords_FullMethodName    = "/lumenvec.DataPlaneTransfer/ExportSealedANNRecords"
	DataPlaneTransfer_ExportANNState_FullMethodName            = "/lumenvec.DataPlaneTransfer/ExportANNState"
	DataPlaneTransfer_SnapshotMutableANNRecords_FullMethodName = "/lumenvec.DataPlaneTransfer/SnapshotMutableANNRecords"
	DataPlaneTransfer_GetDeltaOffset_FullMethodName            = "/lumenvec.DataPlaneTransfer/GetDeltaOffset"
	DataPlaneTransfer_GetVectorCount_FullMethodName            = "/lumenvec.DataPlaneTransfer/GetVectorCount"
	DataPlaneTransfer_ReplayDeltas_FullMethodName              = "/lumenvec.DataPlaneTransfer/ReplayDeltas"
	DataPlaneTransfer_GetANNProfile_FullMethodName             = "/lumenvec.DataPlaneTransfer/GetANNProfile"
)

// DataPlaneTransferClient is the client API for DataPlaneTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataPlaneTransfer is an internal streaming transport for immutable ANN
// artifacts. It is intentionally separate from VectorService: public clients
// cannot stage cluster generations through the data-plane API.
type DataPlaneTransferClient interface {
	ReservePrebuiltIDs(ctx context.Context, in *ReservePrebuiltIDsRequest, opts ...grpc.CallOption) (*ReservePrebuiltIDsResponse, error)
	UploadPrebuiltSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse], error)
	ApplyPrebuiltSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse], error)
	// BuildPrebuiltSegment streams canonical vectors to the owning data node.
	// The destination reserves local IDs, builds the ANN graph and commits the
	// durable generation, avoiding coordinator-side HNSW construction.
	BuildPrebuiltSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse], error)
	ExportSealedANNRecords(ctx context.Context, in *ExportSealedANNRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportSealedANNRecordsResponse], error)
	ExportANNState(ctx context.Context, in *ExportANNStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportANNStateResponse], error)
	SnapshotMutableANNRecords(ctx context.Context, in *SnapshotMutableANNRecordsRequest, opts ...grpc.CallOption) (*SnapshotMutableANNRecordsResponse, error)
	GetDeltaOffset(ctx context.Context, in *GetDeltaOffsetRequest, opts ...grpc.CallOption) (*GetDeltaOffsetResponse, error)
	GetVectorCount(ctx context.Context, in *GetVectorCountRequest, opts ...grpc.CallOption) (*GetVectorCountResponse, error)
	ReplayDeltas(ctx context.Context, in *ReplayDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeltaMutation], error)
	GetANNProfile(ctx context.Context, in *GetANNProfileRequest, opts ...grpc.CallOption) (*GetANNProfileResponse, error)
}

type dataPlaneTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneTransferClient(cc grpc.ClientConnInterface) DataPlaneTransferClient {
	return &dataPlaneTransferClient{cc}
}

func (c *dataPlaneTransferClient) ReservePrebuiltIDs(ctx context.Context, in *ReservePrebuiltIDsRequest, opts ...grpc.CallOption) (*ReservePrebuiltIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservePrebuiltIDsResponse)
	err := c.cc.Invoke(ctx, DataPlaneTransfer_ReservePrebuiltIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneTransferClient) UploadPrebuiltSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[0], DataPlaneTransfer_UploadPrebuiltSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_UploadPrebuiltSnapshotClient = grpc.ClientStreamingClient[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]

func (c *dataPlaneTransferClient) ApplyPrebuiltSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[1], DataPlaneTransfer_ApplyPrebuiltSegment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ApplyPrebuiltSegmentClient = grpc.ClientStreamingClient[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]

func (c *dataPlaneTransferClient) BuildPrebuiltSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[2], DataPlaneTransfer_BuildPrebuiltSegment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_BuildPrebuiltSegmentClient = grpc.ClientStreamingClient[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]

func (c *dataPlaneTransferClient) ExportSealedANNRecords(ctx context.Context, in *ExportSealedANNRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportSealedANNRecordsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[3], DataPlaneTransfer_ExportSealedANNRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportSealedANNRecordsRequest, ExportSealedANNRecordsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ExportSealedANNRecordsClient = grpc.ServerStreamingClient[ExportSealedANNRecordsResponse]

func (c *dataPlaneTransferClient) ExportANNState(ctx context.Context, in *ExportANNStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportANNStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[4], DataPlaneTransfer_ExportANNState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportANNStateRequest, ExportANNStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ExportANNStateClient = grpc.ServerStreamingClient[ExportANNStateResponse]

func (c *dataPlaneTransferClient) SnapshotMutableANNRecords(ctx context.Context, in *SnapshotMutableANNRecordsRequest, opts ...grpc.CallOption) (*SnapshotMutableANNRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotMutableANNRecordsResponse)
	err := c.cc.Invoke(ctx, DataPlaneTransfer_SnapshotMutableANNRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneTransferClient) GetDeltaOffset(ctx context.Context, in *GetDeltaOffsetRequest, opts ...grpc.CallOption) (*GetDeltaOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeltaOffsetResponse)
	err := c.cc.Invoke(ctx, DataPlaneTransfer_GetDeltaOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneTransferClient) GetVectorCount(ctx context.Context, in *GetVectorCountRequest, opts ...grpc.CallOption) (*GetVectorCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVectorCountResponse)
	err := c.cc.Invoke(ctx, DataPlaneTransfer_GetVectorCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneTransferClient) ReplayDeltas(ctx context.Context, in *ReplayDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeltaMutation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneTransfer_ServiceDesc.Streams[5], DataPlaneTransfer_ReplayDeltas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplayDeltasRequest, DeltaMutation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ReplayDeltasClient = grpc.ServerStreamingClient[DeltaMutation]

func (c *dataPlaneTransferClient) GetANNProfile(ctx context.Context, in *GetANNProfileRequest, opts ...grpc.CallOption) (*GetANNProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetANNProfileResponse)
	err := c.cc.Invoke(ctx, DataPlaneTransfer_GetANNProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneTransferServer is the server API for DataPlaneTransfer service.
// All implementations must embed UnimplementedDataPlaneTransferServer
// for forward compatibility.
//
// DataPlaneTransfer is an internal streaming transport for immutable ANN
// artifacts. It is intentionally separate from VectorService: public clients
// cannot stage cluster generations through the data-plane API.
type DataPlaneTransferServer interface {
	ReservePrebuiltIDs(context.Context, *ReservePrebuiltIDsRequest) (*ReservePrebuiltIDsResponse, error)
	UploadPrebuiltSnapshot(grpc.ClientStreamingServer[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]) error
	ApplyPrebuiltSegment(grpc.ClientStreamingServer[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]) error
	// BuildPrebuiltSegment streams canonical vectors to the owning data node.
	// The destination reserves local IDs, builds the ANN graph and commits the
	// durable generation, avoiding coordinator-side HNSW construction.
	BuildPrebuiltSegment(grpc.ClientStreamingServer[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]) error
	ExportSealedANNRecords(*ExportSealedANNRecordsRequest, grpc.ServerStreamingServer[ExportSealedANNRecordsResponse]) error
	ExportANNState(*ExportANNStateRequest, grpc.ServerStreamingServer[ExportANNStateResponse]) error
	SnapshotMutableANNRecords(context.Context, *SnapshotMutableANNRecordsRequest) (*SnapshotMutableANNRecordsResponse, error)
	GetDeltaOffset(context.Context, *GetDeltaOffsetRequest) (*GetDeltaOffsetResponse, error)
	GetVectorCount(context.Context, *GetVectorCountRequest) (*GetVectorCountResponse, error)
	ReplayDeltas(*ReplayDeltasRequest, grpc.ServerStreamingServer[DeltaMutation]) error
	GetANNProfile(context.Context, *GetANNProfileRequest) (*GetANNProfileResponse, error)
	mustEmbedUnimplementedDataPlaneTransferServer()
}

// UnimplementedDataPlaneTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneTransferServer struct{}

func (UnimplementedDataPlaneTransferServer) ReservePrebuiltIDs(context.Context, *ReservePrebuiltIDsRequest) (*ReservePrebuiltIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReservePrebuiltIDs not implemented")
}
func (UnimplementedDataPlaneTransferServer) UploadPrebuiltSnapshot(grpc.ClientStreamingServer[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadPrebuiltSnapshot not implemented")
}
func (UnimplementedDataPlaneTransferServer) ApplyPrebuiltSegment(grpc.ClientStreamingServer[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]) error {
	return status.Error(codes.Unimplemented, "method ApplyPrebuiltSegment not implemented")
}
func (UnimplementedDataPlaneTransferServer) BuildPrebuiltSegment(grpc.ClientStreamingServer[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]) error {
	return status.Error(codes.Unimplemented, "method BuildPrebuiltSegment not implemented")
}
func (UnimplementedDataPlaneTransferServer) ExportSealedANNRecords(*ExportSealedANNRecordsRequest, grpc.ServerStreamingServer[ExportSealedANNRecordsResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportSealedANNRecords not implemented")
}
func (UnimplementedDataPlaneTransferServer) ExportANNState(*ExportANNStateRequest, grpc.ServerStreamingServer[ExportANNStateResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportANNState not implemented")
}
func (UnimplementedDataPlaneTransferServer) SnapshotMutableANNRecords(context.Context, *SnapshotMutableANNRecordsRequest) (*SnapshotMutableANNRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotMutableANNRecords not implemented")
}
func (UnimplementedDataPlaneTransferServer) GetDeltaOffset(context.Context, *GetDeltaOffsetRequest) (*GetDeltaOffsetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeltaOffset not implemented")
}
func (UnimplementedDataPlaneTransferServer) GetVectorCount(context.Context, *GetVectorCountRequest) (*GetVectorCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVectorCount not implemented")
}
func (UnimplementedDataPlaneTransferServer) ReplayDeltas(*ReplayDeltasRequest, grpc.ServerStreamingServer[DeltaMutation]) error {
	return status.Error(codes.Unimplemented, "method ReplayDeltas not implemented")
}
func (UnimplementedDataPlaneTransferServer) GetANNProfile(context.Context, *GetANNProfileRequest) (*GetANNProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetANNProfile not implemented")
}
func (UnimplementedDataPlaneTransferServer) mustEmbedUnimplementedDataPlaneTransferServer() {}
func (UnimplementedDataPlaneTransferServer) testEmbeddedByValue()                           {}

// UnsafeDataPlaneTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneTransferServer will
// result in compilation errors.
type UnsafeDataPlaneTransferServer interface {
	mustEmbedUnimplementedDataPlaneTransferServer()
}

func RegisterDataPlaneTransferServer(s grpc.ServiceRegistrar, srv DataPlaneTransferServer) {
	// If the following call panics, it indicates UnimplementedDataPlaneTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlaneTransfer_ServiceDesc, srv)
}

func _DataPlaneTransfer_ReservePrebuiltIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePrebuiltIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneTransferServer).ReservePrebuiltIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneTransfer_ReservePrebuiltIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneTransferServer).ReservePrebuiltIDs(ctx, req.(*ReservePrebuiltIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneTransfer_UploadPrebuiltSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneTransferServer).UploadPrebuiltSnapshot(&grpc.GenericServerStream[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_UploadPrebuiltSnapshotServer = grpc.ClientStreamingServer[UploadPrebuiltSnapshotRequest, UploadPrebuiltSnapshotResponse]

func _DataPlaneTransfer_ApplyPrebuiltSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneTransferServer).ApplyPrebuiltSegment(&grpc.GenericServerStream[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ApplyPrebuiltSegmentServer = grpc.ClientStreamingServer[ApplyPrebuiltSegmentRequest, ApplyPrebuiltSegmentResponse]

func _DataPlaneTransfer_BuildPrebuiltSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneTransferServer).BuildPrebuiltSegment(&grpc.GenericServerStream[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_BuildPrebuiltSegmentServer = grpc.ClientStreamingServer[BuildPrebuiltSegmentRequest, BuildPrebuiltSegmentResponse]

func _DataPlaneTransfer_ExportSealedANNRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportSealedANNRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneTransferServer).ExportSealedANNRecords(m, &grpc.GenericServerStream[ExportSealedANNRecordsRequest, ExportSealedANNRecordsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ExportSealedANNRecordsServer = grpc.ServerStreamingServer[ExportSealedANNRecordsResponse]

func _DataPlaneTransfer_ExportANNState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportANNStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneTransferServer).ExportANNState(m, &grpc.GenericServerStream[ExportANNStateRequest, ExportANNStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ExportANNStateServer = grpc.ServerStreamingServer[ExportANNStateResponse]

func _DataPlaneTransfer_SnapshotMutableANNRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotMutableANNRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneTransferServer).SnapshotMutableANNRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneTransfer_SnapshotMutableANNRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneTransferServer).SnapshotMutableANNRecords(ctx, req.(*SnapshotMutableANNRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneTransfer_GetDeltaOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeltaOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneTransferServer).GetDeltaOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneTransfer_GetDeltaOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneTransferServer).GetDeltaOffset(ctx, req.(*GetDeltaOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneTransfer_GetVectorCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneTransferServer).GetVectorCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneTransfer_GetVectorCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneTransferServer).GetVectorCount(ctx, req.(*GetVectorCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneTransfer_ReplayDeltas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplayDeltasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneTransferServer).ReplayDeltas(m, &grpc.GenericServerStream[ReplayDeltasRequest, DeltaMutation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneTransfer_ReplayDeltasServer = grpc.ServerStreamingServer[DeltaMutation]

func _DataPlaneTransfer_GetANNProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetANNProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneTransferServer).GetANNProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneTransfer_GetANNProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneTransferServer).GetANNProfile(ctx, req.(*GetANNProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPlaneTransfer_ServiceDesc is the grpc.ServiceDesc for DataPlaneTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlaneTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumenvec.DataPlaneTransfer",
	HandlerType: (*DataPlaneTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReservePrebuiltIDs",
			Handler:    _DataPlaneTransfer_ReservePrebuiltIDs_Handler,
		},
		{
			MethodName: "SnapshotMutableANNRecords",
			Handler:    _DataPlaneTransfer_SnapshotMutableANNRecords_Handler,
		},
		{
			MethodName: "GetDeltaOffset",
			Handler:    _DataPlaneTransfer_GetDeltaOffset_Handler,
		},
		{
			MethodName: "GetVectorCount",
			Handler:    _DataPlaneTransfer_GetVectorCount_Handler,
		},
		{
			MethodName: "GetANNProfile",
			Handler:    _DataPlaneTransfer_GetANNProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPrebuiltSnapshot",
			Handler:       _DataPlaneTransfer_UploadPrebuiltSnapshot_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ApplyPrebuiltSegment",
			Handler:       _DataPlaneTransfer_ApplyPrebuiltSegment_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BuildPrebuiltSegment",
			Handler:       _DataPlaneTransfer_BuildPrebuiltSegment_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportSealedANNRecords",
			Handler:       _DataPlaneTransfer_ExportSealedANNRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExportANNState",
			Handler:       _DataPlaneTransfer_ExportANNState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReplayDeltas",
			Handler:       _DataPlaneTransfer_ReplayDeltas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
